# Generated by Django 4.0.1 on 2024-05-17 13:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(max_length=10)),
                ('age', models.PositiveIntegerField()),
                ('region', models.CharField(max_length=100)),
                ('education', models.CharField(max_length=100)),
                ('relationship_status', models.CharField(max_length=100)),
                ('occupation', models.CharField(max_length=100)),
                ('household_income', models.CharField(max_length=100)),
                ('social_class', models.CharField(max_length=100)),
                ('smoking_frequency', models.CharField(max_length=100)),
                ('credit_card_debt', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Response',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.TextField()),
                ('answered_at', models.DateTimeField(auto_now_add=True)),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='surveys.participant')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='surveys.question')),
            ],
            options={
                'unique_together': {('question', 'participant')},
            },
        ),
    ]
