# Generated by Django 4.0.1 on 2024-05-21 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0002_alter_participant_age_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='no_percentage',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='question',
            name='yes_percentage',
            field=models.FloatField(default=0),
        ),
    ]
